currencies:
    G11: ['AUD','CAD','JPY','NZD','NOK','GBP','SEK','CHF','USD','DKK']
    CEEMEA: ['RUB','TRY']
    Africa: ['ZAR']
    EM_Asia: ['HKD','INR','SGD','TWD','CNY','KRW']
    EM_Latam: ['BRL','MXN']